spring:
  application:
    name: website
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

---

spring:
  profiles: docker
  application:
    name: website
  cloud:
    consul:
      host: consul
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false
